[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "about"
    name = "Projects"
    url = "/projects"
    weight = 2

[[main]]
    identifier = "categories"
    name = "CV"
    url = "/resume"
    weight = 3
    
# Social Media Configuration

[[social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/dhruvshrivastava/"
    weight = 1

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/dhruvshrivastava"
    weight = 2